CREATE TABLE EXUSER (
	EXUSER_ID VARCHAR2(30),
	EXUSER_PASS VARCHAR2(30),
	EXUSER_NAME VARCHAR2(20),
	EXUSER_AGE NUMBER,
	EXUSER_GENDER VARCHAR2(5),
	EXUSER_EMAIL VARCHAR2(30),
	PRIMARY KEY(EXUSER_ID)
);
